// Generated by CodiumAI
import { it, describe, expect } from 'vitest'
import { manufacture } from './manufacture'

describe('manufacture', () => {
  // Should return an empty array when gifts is an empty array and materials is any string
  it('should return an empty array when gifts is an empty array and materials is any string', () => {
    const gifts = []
    const materials = 'abc'

    const result = manufacture(gifts, materials)

    expect(result).toEqual([])
  })

  // Should return an empty array when gifts is any non-empty array and materials is an empty string
  it('should return an empty array when gifts is any non-empty array and materials is an empty string', () => {
    const gifts = ['tren', 'oso']
    const materials = ''

    const result = manufacture(gifts, materials)

    expect(result).toEqual([])
  })

  // Should return an array with all gifts when all gifts can be made with the available materials
  it('should return an array with all gifts when all gifts can be made with the available materials', () => {
    const gifts = ['tren', 'oso']
    const materials = 'tronesa'

    const result = manufacture(gifts, materials)

    expect(result).toEqual(['tren', 'oso'])
  })

  // Should return an empty array when gifts is any non-empty array and materials does not contain any character required to make any gift
  it('should return an empty array when gifts is any non-empty array and materials does not contain any character required to make any gift', () => {
    const gifts = ['tren', 'oso']
    const materials = 'abc'

    const result = manufacture(gifts, materials)

    expect(result).toEqual([])
  })

  // Should return an empty array when gifts is any non-empty array and materials does not contain all characters required to make any gift
  it('should return an empty array when gifts is any non-empty array and materials does not contain all characters required to make any gift', () => {
    const gifts = ['juego', 'puzzle']
    const materials = 'jlepuz'

    const result = manufacture(gifts, materials)

    expect(result).toEqual(['puzzle'])
  })

  // Should return an empty array when gifts is any non-empty array and materials contains only one character required to make any gift
  it('should return an empty array when gifts is any non-empty array and materials contains only one character required to make any gift', () => {
    const gifts = ['libro', 'ps5']
    const materials = 'psli'

    const result = manufacture(gifts, materials)

    expect(result).toEqual([])
  })
})
